[workspace]
members = [
    "zap",
    "zap-core",
    "zap-server",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
