[package]
name = "zap"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tcp_repl"
path = "./src/tcp_repl.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#regex = "1.5"
